### ISSUE TITLE
デザイナー管理情報

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/designer-management#60]

**Comment by writerityyuko** [comment]
@writerity-watanabe 

開地さんから、
PCやデザイナーの更新時期の情報を開地さんがまとめられているスプレッドシートに入れたいが、
どこかにまとまっていたりしますか、と、
お問い合わせがあったのですが、
渡邊さんのほうでまとめているデータがありますでしょうか？

**Comment by writerity-watanabe** [comment]
@writerityyuko 
先ほどの件でしたね。見落としていました！
