### ISSUE TITLE
デザイナー使用PCの管理番号

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/designer-management#62]
asset management number

https://docs.google.com/spreadsheets/d/1K_erfEuMj77F-CaJb2BY-JOPgws2yZ5Vu2mB8Vt7fXY/edit#gid=0

**Comment by writerityyuko** [comment]
@writerity-watanabe 

デザイナーが使っているパソコンの管理の一つとして、それぞれのマシンにライタリティの資産管理番号を付与したいのですが、いかがでしょうか？

SACからデザイナー管理用のデータシートを共有されているのですが、誰がどのパソコンを使っていて、リース期間はどれくらいで、みたいなことが一覧できるようにしたいようなのです。

パソコンの製造番号でもよいのですが、まぁ、会社っぽく、資産管理番号とかつけたほうが、資産管理の面からも便利かなと思ったので。

もし、すでに相応する管理番号があれば、ご教示くださいー。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
はい、問題ありません！
一旦製造番号とかで良いかなーと思っていましたが、管理番号付与してしまって大丈夫です。

**Comment by writerityyuko** [comment]
@writerity-watanabe 

ありがとうございます。
では、デザイナーのパソコン用に資産管理番号を付与したら、データをまとめて共有しますね。

**Comment by writerityyuko** [comment]
@writerity-watanabe 

例の資産管理番号の付与についてルールを決めてみました。
これでよければ、デザイナーたちのパソコンから番号付けていき、
あとはエレナにでも引き継いでもら追うかなと思ってます。

https://docs.google.com/spreadsheets/d/1K_erfEuMj77F-CaJb2BY-JOPgws2yZ5Vu2mB8Vt7fXY/edit#gid=0

**Comment by writerity-watanabe** [comment]
@writerityyuko 
はい、問題ないです！

**Comment by writerityyuko** [comment]
@writerity-watanabe 

承知しましたー。

どうでもいことですが、ナンバリングの後、資産管理のシールとか貼りますか？（マケドニアにあるのかわかんないですけど。。）

**Comment by writerity-watanabe** [comment]
@writerityyuko 
いちいちシリアル番号見たりするのも面倒なので
シール貼ってしまいましょう。
エレナに適当に手作りしてもらえば良いかなーと思います。

**Comment by writerityyuko** [comment]
@writerity-watanabe 

承知しましたー。エレナが好きそうな仕事ですー。
