### ISSUE TITLE
Adobeアカウントの契約期限の確認

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/designer-management#64]

**Comment by writerityyuko** [comment]
@writerity-watanabe 

またまたアドビアカウントの件なのですが、
今使っているアカウントの契約期限について質問がいくつかあります。
（SACの管理シートに記入を依頼されているため）

お手数ですが、ご存知の範囲で教えていただけますでしょうか？

ちなみに、SACには求められている情報（契約期限）だけをシェアします。
以下は、私の理解のためです（聞かれたときに、今だと、何が何だかよくわからないので。）

Q１．デザイナーたちのアカウントは、Adobe Creative Cloudのアカウントですか？

Q２．（Q１がyesの場合のみ）月額支払いのサービスなので、使用期限などはないという認識で合ってますか？

Q３．（Q１がyesの場合のみ）Adobe Creative Cloudの契約プランは、「Creative Cloud コンプリートプラン個人向け」で合ってますか？（使えるソフトウェアの確認のための質問です）

Q４．（Q１がNoの場合のみ）各ソフトウェアごとに契約をしていますか？それともほかの契約形態があるのでしょうか？

Q5.（Q4がYesの場合のみ）契約プラン（単体プランorコンプリートプラン、年間プランor月々プラン）を教えてください。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
> Q１．デザイナーたちのアカウントは、Adobe Creative Cloudのアカウントですか？
> Q２．（Q１がyesの場合のみ）月額支払いのサービスなので、使用期限などはないという認識で合ってますか？

はい！その認識で間違い無いかと思います。
> Q３．（Q１がyesの場合のみ）Adobe Creative Cloudの契約プランは、「Creative Cloud コンプリートプラン個人向け」で合ってますか？（使えるソフトウェアの確認のための質問です）

シートにもありますが、Ps,Ae,Aiのみです！

**Comment by writerityyuko** [comment]
@writerity-watanabe 

> シートにもありますが、Ps,Ae,Aiのみです！

先日デザイナーたちに使えるソフトを聞いたところ、
Ps　Ae　Ai　に加えて、Pr　と　media encoder CC　も使っているという回答が来ましたので、あれ？と思ってもう一度デザイナー達に確認したところ、

・それぞれAdobe Creative Cloudコンプリートプラン（全部のソフト使えるやつ）のアカウントを保有
・現在ダウンロードして使っているのが、Ps, Ae, Ai, Pr, media encoder CC　（ZnarkoはAnimateも）で、使おうと思えば他のも使える

ということで、やっといろいろ不明な点がつながりました。失礼しました。

支払い契約は「年間プラン一括払い」で契約をされていて、たぶん自動更新なので契約期限の管理はしなくても大丈夫、ということですね。承知しました。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
はい、よろしくお願いします！
