### ISSUE TITLE
デザイナーの管理業務について

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/designer-management#65]

**Comment by writerityyuko** [comment]
@writerity-watanabe 

> 基本的に開地さんとの話では、坂口さんに管理してほしいとのニュアンスでしたが、

そうなんですよ。でも、時川さんの意向もあるかなーとか、そんなにがっつり入ってよいのか迷ったたんです。

でも、わかりました。面談、契約更新、ウイルスチェックとか、日々の業務チェックとか、やっていくにあたり、いろいろお伺いしたいこともあるので、一度ミーティングをお願いしたいと思います！

私は9:00から14:00までの間ならいつでもOKです。
ご都合のよい日時をお知らせくださいー。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
承知です！
明日の13時、お願いします！

**Comment by writerityyuko** [comment]
@writerity-watanabe 

お忙しいところありがとうございますー。
では明日の13;00で。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
すみません、カイがリサーチの件でも坂口さんと話したいとのことだったので
10時半からでも良いでしょうか？
→その後、11時からカイとリサーチの件でミーティング（もしくはリサーチについては13時からでも）

**Comment by writerityyuko** [comment]
@writerity-watanabe 

> デザイナ管理の件、10時半からでも良いでしょうか？
> →その後、11時からカイとリサーチの件でミーティング

承知しました。大丈夫ですー。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
よろしくお願いします！
