### ISSUE TITLE
メーリングリストへの追加依頼

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/designer-management#72]

**Comment by writerityyuko** [comment]
@writerity-watanabe 

デザイナーがSACとのやり取りに使っている（？）メーリングリストに、
私も使いしてもらうことはできますか？
デザイナーのアサイン状況などの確認のためです。

skopje@ml.trs.sub.jp

ご検討お願いしますー。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
入れておきます！
メーリングリストに入れると、「skopje@ml.trs.sub.jp」宛にSACがシステムからタスク依頼メールを送り、それが坂口さんのメールにも転送される感じです！

また完了次第ご連絡します。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
完了しました！
完了メールがwriterity.yuko.sakaguchi@gmail.com宛に届くはずです。

**Comment by writerityyuko** [comment]
@writerity-watanabe 

ありがとございまーす。
完了メール来ました。
