### ISSUE TITLE
開地さんとのミーティング

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/designer-management#73]
明日(2/6)以降で開地さん都合でミーティングの日程決めても良いでしょうか？

▼議題
坂口さんの業務量についてのヒアリング・開地さんとの認識合わせ

**Comment by writerityyuko** [comment]
@writerity-watanabe 

はい！お任せします！失礼しました（＞＜）

**Comment by writerity-watanabe** [comment]
@writerityyuko 
承知です！
