### ISSUE TITLE
[デザイナ面談]３月スケジュール調整

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/designer-management#79]
2/12時点、6名
- Dimitar
- Zarko
- Mirjana
- Oliver
- Andrej
- Aleksander

**Comment by writerity-watanabe** [comment]
@writerityyuko 
３月から3ヶ月ごとに面談を、となっているので２月中に決めておきたいと思います。
＊3/20までに全員完了させる

まず新人2名がいますので、この2名＋Dimitar（新人2名の印象などを聞きたいので）を僕で面談したいと思いますが、良いでしょうか？

特にどの日にやって欲しい等はないので、3/20までに完了できれば問題ありません。

**Comment by writerityyuko** [comment]
@writerity-watanabe 

> ▼面談担当について
> まず新人2名がいますので、この2名＋Dimitar（新人2名の印象などを聞きたいので）を僕で面談したいと思いますが、良いでしょうか？

はい。もちろんですー。宜しくお願いします。

日程についても承知しました。
順次スケジュールを組んで、3月の第2週までには3人分終わらせるようにします。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
承知しました！
