### ISSUE TITLE
announcement for designers personal interview

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/designer-management#80]
We will restart to have a personal  interview from March.
It will be held on every 3 months, and we would like to schedule all interviews between and of February and 15th March.

Interviewers are below,
Dimitar, Andrej, Aleksandar　: Hide
Mirijana, Zharko, Oliver   : Yuko

This interview is to see how your current work situation or environment is;  not for assessment or salary negotiation.  (So please relax to have it.)

Soon each interviewer will contact you about schedule.
Thank you in advance.

schedule must be after 13:00; after JP closing

**Comment by writerityyuko** [comment]
@writerity-watanabe 

3か月面談の件、上記のメッセージをチャットワークで流そうと思ってますが、いかがでしょうか？

**Comment by writerity-watanabe** [comment]
@writerityyuko 
はい、大丈夫です！
ありがとうございます。
