### ISSUE TITLE
1on1面談　聞く内容

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/designer-management#95]
以下の4点を、定点観測的に聞いて、今後時系列で本人の意識の変化などを見られる機会として利用する。

**1.これまでの業務・現在の状況**
　1)仕事の満足度を100点満点で言うと何点？思い浮かんだ数字を教えてください。
　2)その点数をつけた背景、理由を教えてください。

**2.少し先（半年後）の話**　
　以下のうち、各人にフィットする質問をチョイス。
　1)半年後、どういう自分になっていたいか？
　2)どういう仕事をしていたいか？
　3)どういう立ち位置（ポジション）でいたいか？
　4)どういうチームにしたいか？
　5)どんな気持ちでいたいか？

**3.周りの人との人間関係**
　1)誰と話すことが多いか？
　2)ランチや飲みに行く人は？
　3)仕事上で絡みがある人は？
　4)やりやすい人、やりにくい人はいるか？

**4.なんでも相談・要望**
　何か相談したいこと、その場で思いついたことでもよいので要望があれば伝えてもらう。

**Comment by writerityyuko** [comment]
@writerity-watanabe 

なんか、せっかく面談設定して、5分で終わる内容の薄い面談だと「は？やる意味ある？」ってなっちゃうと思うので、上記の感じのことをみんなに同じように聞いて、メンバー間の比較、あるいは同じ人物の時系列での比較ができるようにしたらいいのかな、と思ってます。
想定は15分から30分です。

ご参考まで。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
ヒアリングシート作ってみました。
まとめるのも面倒なので。。

別シートにコピーして適当に改変すれば、まとめる手間が省けるかと！
https://docs.google.com/spreadsheets/d/1FrPm2a1vzKJt9zu6TvtsPE7YVDtAncrqt6MLGo3xoD0/edit#gid=1522459214

**Comment by writerityyuko** [comment]
@writerity-watanabe 

わ。なんかすごいシートが来た。
デベロッパーのほうも結構管理強める感じなんですかね？
いずれにすても、シートの作成ありがとうございました。

こちら、各人ごとにコピーして、聴取内容を記入していくことにします。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
ちょうど、目標シートを昨日から作成していて、面談の内容について共有いただいたので、
そのまま使っちゃおう！という感じで作成しました。
ディベロッパーの方は、管理というか、まずはコミュニケーションを増やし、しっかり目標を設定してあげることから始めたいと思っています。

よろしくお願いします！
